% --- File: find_optimal_strategy.m (Modified - km_constraint removed) ---
function [best_strategy, min_time, results_matrix, possible_K, possible_M] = find_optimal_strategy(race_params, tire_models, use_uncertainty)
    % Finds the optimal strategy.
    % If use_uncertainty=true, searches over (K,M) dynamic strategy using GA.
    % If use_uncertainty=false, searches over fixed 1/2-stop strategies (example grid search).

    disp('Finding Optimal Strategy...');
    min_time = Inf;
    best_strategy = [];
    results_matrix = []; % GA doesn't naturally produce this for heatmap
    possible_K = [];     % GA doesn't naturally produce this
    possible_M = [];     % GA doesn't naturally produce this

    if use_uncertainty
        % --- Setup Genetic Algorithm for (K, M) ---
        strategy_type = 'dynamic_KM';
        disp('Searching over (K, M) dynamic strategies using Genetic Algorithm...');

        % Define the objective function handle for GA
        % It takes a vector [K, M] and returns the expected time
        % Make sure evaluate_strategy is accessible (either in the same folder or on MATLAB path)
        objectiveFunction = @(vars) evaluate_strategy(vars, race_params, tire_models, true, strategy_type);

        numberOfVariables = 2; % We are optimizing K and M

        % Define bounds for K and M
        min_M_bound = 10; % Lower bound for M
        max_M_bound = race_params.num_laps - 5; % Upper bound for M
        min_K_bound = 1;  % Lower bound for K
        max_K_bound = max_M_bound - 1; % Upper bound for K (must be < M)

        lb = [min_K_bound, min_M_bound]; % Lower bounds [K, M]
        ub = [max_K_bound, max_M_bound]; % Upper bounds [K, M]

        % Specify that both variables are integers
        IntCon = [1, 2];

        % Define the non-linear constraint K < M using the separate function file
        % Make sure km_constraint.m is in the same folder or on MATLAB path
        constraintFunction = @km_constraint;

        % Set GA options (can be tuned)
        % Ensure you have the Global Optimization Toolbox installed
        options = optimoptions('ga', ...
            'Display', 'iter', ... % Show progress ('off', 'iter', 'final')
            'PopulationSize', 50, ... % Number of individuals per generation
            'MaxGenerations', 100, ... % Number of iterations (adjust as needed)
            'PlotFcn', {@gaplotbestf, @gaplotstopping}, ... % Optional: plot progress
            'UseParallel', false); % Set to true if Parallel Computing Toolbox is available and desired

        % --- Run the Genetic Algorithm ---
        fprintf('Running Genetic Algorithm...\n');
        [best_vars, min_time] = ga(objectiveFunction, numberOfVariables, ...
                                   [], [], [], [], lb, ub, ...
                                   constraintFunction, IntCon, options);

        % Assign the best strategy found by GA
        best_strategy = round(best_vars); % Ensure K, M are integers

        fprintf('>>> GA finished. Best strategy found (K=%d, M=%d): Expected Time = %.2f\n', ...
                best_strategy(1), best_strategy(2), min_time);
        % Note: results_matrix, possible_K, possible_M are not generated by GA

    else
        % --- Search over Fixed Strategies (Deterministic Example: 1-stop) ---
        % (Keep your existing grid search code here for the deterministic case)
        strategy_type = 'fixed';
        disp('Searching over fixed 1-stop strategies (deterministic)...');
        num_laps = race_params.num_laps;
        min_pit_lap = 5;
        max_pit_lap = num_laps - 5;
        start_compound_idx = race_params.start_compound_idx;
        available_compounds = 1:length(tire_models);
        next_compounds = available_compounds(available_compounds ~= start_compound_idx);

        for pit_lap = min_pit_lap:max_pit_lap
            stint1_laps = pit_lap;
            stint2_laps = num_laps - pit_lap;
            if stint1_laps <= 0 || stint2_laps <= 0, continue; end

            for c2 = next_compounds % Iterate through valid next compounds
                strategy_params = [start_compound_idx, stint1_laps; c2, stint2_laps]; % Fixed strategy matrix
                current_time = evaluate_strategy(strategy_params, race_params, tire_models, false, strategy_type);

                if current_time < min_time
                    min_time = current_time;
                    best_strategy = strategy_params; % Best strategy is the matrix
                    fprintf('>>> New best fixed (Pit Lap %d, %s -> %s): Time = %.2f\n', ...
                            pit_lap, tire_models(start_compound_idx).name, tire_models(c2).name, min_time);
                end
            end
        end
         fprintf('Finished evaluating fixed strategies.\n');
         % Add logic for 2-stops etc. if needed for deterministic case
    end

    disp('Optimization Finished.');
end

% --- km_constraint function removed from this file ---
% --- It should now be in its own km_constraint.m file ---
