
% Main script to run the F1 Race Strategy Optimization for 1 Track

clear; clc; close all; % Start with a clean workspace

fprintf('F1 Race Strategy Optimization - MATLAB\n');
fprintf('=======================================\n');
fprintf('Start Time: %s\n\n', datestr(now));

% Configuration
USE_UNCERTAINTY = true; % true: Optimize (K,M) using GA | false: Optimize fixed strategy (Grid Search)
RACE_YEAR = 2025; % Specify the year for data loading
RACE_NAME = 'Australian Grand Prix'; % Specify the race name
DATA_FOLDER = 'data'; % Subfolder where CSV files are located

% Load Parameters and Models
fprintf('--- Loading Parameters and Models ---\n');
race_params = define_race_parameters(RACE_YEAR, RACE_NAME); % Pass info if needed
% --- Data-Driven Tire Models ---
csv_filename = sprintf('%d-%s-Practice 2.csv', RACE_YEAR, RACE_NAME); % Choose Practice 2, 3 or Race
csv_filepath = fullfile(DATA_FOLDER, csv_filename); % Construct full path
target_driver = 'VER'; % Example driver
target_compound_name = 'MEDIUM'; % Example compound
target_stint = 1; % Example stint number

try
    tire_models = define_data_driven_tire_models(csv_filepath, target_driver, target_compound_name, target_stint);
catch ME
    warning('Could not load data-driven tire models. Using placeholder models. Error: %s', ME.message);
    tire_models = define_placeholder_tire_models();
end

% --- Validate Inputs ---
if isempty(tire_models) || isempty(race_params)
    error('Failed to load parameters or tire models.');
end
if race_params.num_laps <= 0, error('Number of laps must be positive.'); end
fprintf('-------------------------------------\n\n');

% --- Run Optimization ---
fprintf('--- Starting Optimization (Using Genetic Algorithm) ---\n');
tic;
try
    [optimal_strategy, min_objective_value, ~, ~, ~] = ...
        find_optimal_strategy(race_params, tire_models, USE_UNCERTAINTY);
catch ME
    fprintf('\nError during optimization: %s\n', ME.message);
    fprintf('Stack trace:\n');
    disp(ME.getReport());
    optimal_strategy = [];
    min_objective_value = Inf;
end
elapsed_time = toc;
fprintf('--- Optimization Finished ---\n');

% --- Display Results ---
fprintf('\n--- Optimal Strategy Found ---\n');
if ~isempty(optimal_strategy) && isfinite(min_objective_value)
    if USE_UNCERTAINTY
        fprintf('Strategy Type: Dynamic (K, M) - Optimized using GA\n');
        fprintf('Optimal K (Pit if SC >= Lap K): %d\n', optimal_strategy(1));
        fprintf('Optimal M (Mandatory Pit Lap):  %d\n', optimal_strategy(2));
        fprintf('Minimum Expected Race Time:     %.2f seconds\n', min_objective_value);
    else
        % ... (Display logic for fixed strategy) ...
         fprintf('Strategy Type: Fixed - Optimized using Grid Search\n');
        fprintf('Minimum Race Time (Deterministic): %.2f seconds\n', min_objective_value);
        fprintf('Strategy:\n');
        num_stints = size(optimal_strategy, 1);
        total_laps_in_strategy = 0;
        for i = 1:num_stints
            compound_idx = optimal_strategy(i, 1);
            laps = optimal_strategy(i, 2);
            total_laps_in_strategy = total_laps_in_strategy + laps;
            tire_name = 'Unknown';
            if compound_idx > 0 && compound_idx <= length(tire_models)
                tire_name = tire_models(compound_idx).name;
            end
            fprintf('  Stint %d: %s Tires for %d laps (End Lap: %d)\n', ...
                    i, tire_name, laps, total_laps_in_strategy);
        end
         fprintf('Total laps in strategy: %d (Race laps: %d)\n', sum(optimal_strategy(:,2)), race_params.num_laps);
    end
else
    fprintf('No valid strategy found or optimization failed.\n');
end

fprintf('\nOptimization Computation Time: %.2f seconds\n', elapsed_time);

% --- Deliverable Visuals ---
fprintf('\n--- Generating Visuals ---\n');

% 1. Tire Fit Plot: Generated automatically by fit_tire_model_from_csv if successful.
fprintf(' Visual 1: Check for figure window titled "Tire Fit: ..."\n');

% 2. GA Convergence Plots: Generated automatically by the 'ga' function.
fprintf(' Visual 2: Check for figure windows generated by GA (Best Fitness, Stopping Criteria).\n');

% 3. Comparison Bar Chart (Requires evaluating baseline strategies)
if USE_UNCERTAINTY && ~isempty(optimal_strategy) && isfinite(min_objective_value)
    fprintf(' Evaluating baseline strategies for comparison plot...\n');
    try
        % --- Evaluate Baseline Strategy 1: Example Naive (K, M) ---
        naive_KM_strategy = [15, 30]; % Example: Pit early under SC, mandatory pit lap 30
        expected_time_naive = evaluate_strategy(naive_KM_strategy, race_params, tire_models, true, 'dynamic_KM');
        fprintf('  Naive Strategy [%d, %d] Expected Time: %.2f s\n', naive_KM_strategy(1), naive_KM_strategy(2), expected_time_naive);

        % --- Evaluate Baseline Strategy 2: Example Fixed 1-Stop (Deterministic-based) ---
        % Find a reasonable deterministic 1-stop lap first (can reuse parts of find_optimal_strategy's 'else' block)
        % For simplicity, let's just pick a plausible lap, e.g., lap 25
        fixed_pit_lap = 25;
        start_compound_idx = race_params.start_compound_idx;
        next_compounds = find((1:length(tire_models)) ~= start_compound_idx);
        if isempty(next_compounds), next_compound_idx_fixed = start_compound_idx; else next_compound_idx_fixed = next_compounds(1); end
        fixed_strategy_matrix = [start_compound_idx, fixed_pit_lap; next_compound_idx_fixed, race_params.num_laps - fixed_pit_lap];
        % Evaluate this fixed strategy *under uncertainty* using evaluate_strategy
        % NOTE: evaluate_strategy currently doesn't handle uncertainty for 'fixed' type.
        %       You would need to modify evaluate_strategy or simulate_race_fixed to include SC logic.
        %       For now, we'll use a placeholder value.
        expected_time_fixed_placeholder = min_objective_value * 1.02; % Placeholder: 2% worse than optimal
        fprintf('  Fixed Strategy (Lap %d) Expected Time: %.2f s (Placeholder)\n', fixed_pit_lap, expected_time_fixed_placeholder);

        % --- Create Bar Chart ---
        figure('Name', 'Strategy Comparison');
        bar_data = [min_objective_value, expected_time_naive, expected_time_fixed_placeholder];
        bar_labels = {sprintf('Optimal GA (K=%d, M=%d)', optimal_strategy(1), optimal_strategy(2)), ...
                      sprintf('Naive (K=%d, M=%d)', naive_KM_strategy(1), naive_KM_strategy(2)), ...
                      sprintf('Fixed 1-Stop (L%d - Placeholder)', fixed_pit_lap)};
        b = bar(bar_data);
        set(gca, 'xticklabel', bar_labels);
        ylabel('Expected Total Race Time (seconds)');
        title(sprintf('Comparison of Expected Race Times (%s)', RACE_NAME));
        grid on;
        ylim([min(bar_data)*0.98, max(bar_data)*1.02]); % Adjust y-axis limits
        xtips = b.XEndPoints;
        ytips = b.YEndPoints;
        labels = string(round(b.YData,1));
        text(xtips,ytips,labels,'HorizontalAlignment','center',...
            'VerticalAlignment','bottom'); % Add values on top of bars
        fprintf(' Visual 3: Displayed Strategy Comparison Bar Chart.\n');

    catch ME_compare
        warning('Could not generate comparison plot: %s', ME_compare.message);
    end
end

% 4. Result Distribution Histogram (Requires re-running simulation for optimal strategy)
if USE_UNCERTAINTY && ~isempty(optimal_strategy) && isfinite(min_objective_value)
     fprintf(' Re-simulating optimal strategy for distribution plot...\n');
     try
        % Re-run evaluate_strategy, but modify it to return all simulation times
        % OR: Copy the Monte Carlo loop here
        num_sims_hist = race_params.num_simulations_for_expected_time; % Use same number
        simulation_times_hist = zeros(num_sims_hist, 1);
        K_opt = optimal_strategy(1);
        M_opt = optimal_strategy(2);
        start_compound_idx = race_params.start_compound_idx;
        available_compounds = 1:length(tire_models);
        next_compound_idx = find(available_compounds ~= start_compound_idx, 1, 'first');
        if isempty(next_compound_idx) && length(tire_models) > 1 && race_params.must_use_different_compound, next_compound_idx = start_compound_idx; end
        if isempty(next_compound_idx), next_compound_idx = start_compound_idx; end % Handle single compound case

        for i = 1:num_sims_hist
            % --- Copy Monte Carlo Simulation Logic from evaluate_strategy ---
            total_time_run = 0; current_lap_run = 0; laps_on_current_tire_run = 0;
            current_compound_idx_run = start_compound_idx; pitted_run = false;
            while current_lap_run < race_params.num_laps
                current_lap_run = current_lap_run + 1; laps_on_current_tire_run = laps_on_current_tire_run + 1;
                tire = tire_models(current_compound_idx_run); base_time = tire.base_lap_time;
                degradation = tire.degradation_func(laps_on_current_tire_run); lap_time = base_time + degradation;
                pit_decision_this_lap = false; pit_cost_this_lap = 0;
                if ~pitted_run
                    sc_occurred_this_lap = (rand() < race_params.safety_car_probability_per_lap);
                    if sc_occurred_this_lap && current_lap_run >= K_opt
                        pit_decision_this_lap = true; pit_cost_this_lap = race_params.pit_stop_time_loss_sc;
                    elseif current_lap_run == M_opt
                         pit_decision_this_lap = true; pit_cost_this_lap = race_params.pit_stop_time_loss;
                    end
                    if pit_decision_this_lap
                        pitted_run = true; current_compound_idx_run = next_compound_idx; laps_on_current_tire_run = 0;
                    end
                end
                total_time_run = total_time_run + lap_time;
                if pit_decision_this_lap, total_time_run = total_time_run + pit_cost_this_lap; end
            end
            simulation_times_hist(i) = total_time_run;
             % --- End Copied Logic ---
        end

        % --- Create Histogram ---
        figure('Name', 'Optimal Strategy Result Distribution');
        histogram(simulation_times_hist, 50); % Use 50 bins, adjust as needed
        hold on;
        xline(min_objective_value, 'r--', 'LineWidth', 2, 'Label', sprintf('Mean = %.2fs', min_objective_value));
        xlabel('Simulated Total Race Time (seconds)');
        ylabel('Frequency (Number of Simulations)');
        title({sprintf('Distribution of Race Times for Optimal Strategy (K=%d, M=%d)', optimal_strategy(1), optimal_strategy(2)), ...
               sprintf('%d Simulations, SC Prob=%.2f', num_sims_hist, race_params.safety_car_probability_per_lap)});
        grid on;
        hold off;
        fprintf(' Visual 4: Displayed Result Distribution Histogram.\n');

     catch ME_hist
         warning('Could not generate distribution plot: %s', ME_hist.message);
     end
end


fprintf('\n--- End of Simulation ---\n');
